### ISSUE TITLE
Problem Unable to autoload constant (/localtower/dashboard)

### ISSUE THREAD

**Issue by Turkish** [damln/localtower#1]
Unable to autoload constant,  expected model to define it

**Comment by damln** [comment]
Hi @Turkish!

Can you detail your Rails version, your PostgreSQL version, and copy/paste the full stack trace?

**Comment by damln** [comment]
Maybe this commit solves this. Can you try @Turkish ?
https://github.com/damln/localtower/commit/341be1f863c2c11b81fd2ca22505b6f8add12e77
