### ISSUE TITLE
Rails 5.1

### ISSUE THREAD

**Issue by bbenezech** [damln/localtower#11]
Hi,

Is the lock `< 5.1` since `0.2.3` intentional, do you have a Rails 5.1 related issue?

**Comment by damln** [comment]
Yes I saw issues in the Engine, I'm going to investigate next week.

**Comment by bbenezech** [comment]
Oh ok. Sorry for the noise.

**Comment by damln** [comment]
@bbenezech It's solved in 0.3.1 :)
Localtower now supports 4.2+ apps (Rails 5.1 included)

```bash
bundle update localtower
```
