### ISSUE TITLE
Option to opt a relation between models

### ISSUE THREAD

**Issue by siva-wal** [damln/localtower#8]
Thanks for the great gem!!! In right time this gem rescued me from schema and migration problems. While I am using this gem, I found that we can't opt a relation between two models. Could we add this feature ? 

Again thanks for the great effort!!!!

**Comment by damln** [comment]
Hi @siva-wal !

Thanks for your kind comment.

Do you have a more descriptive way to express your needs regarding relations?
I'm very open to improve the UI and create new ways to link models and more.

I just want to be sure I understand your use case.
Don't hesitate to draw something even very basic and upload it here ;)

**Comment by damln** [comment]
Should be solved with version [0.4.1](https://rubygems.org/gems/localtower/versions/0.4.1)
